export {};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      EXPO_PUBLIC_API_BASE: string;
      EXPO_PUBLIC_API_STAGING_BASE: string;
      EXPO_PUBLIC_API_ORIGIN: string;
      EXPO_PUBLIC_API_USER_AGENT: string;
      EXPO_PUBLIC_API_AUTHORIZATION: string;

      EXPO_PUBLIC_URL_DEVELOPMENT: string;
      EXPO_PUBLIC_URL_PRODUCTION: string;
      EXPO_PUBLIC_AUTH_SECRET: string;
      EXPO_PUBLIC_MONGODB_PASSWORD: string;
      EXPO_PUBLIC_UPSTASH_REDIS_REST_URL: string;
      EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN: string;
      EXPO_PUBLIC_APPWRITE_CLIENT_ID: string;
      EXPO_PUBLIC_APPWRITE_BUCKET_ID: string;
      EXPO_PUBLIC_APPWRITE_EDITORIAL_BUCKET_ID: string;
      EXPO_PUBLIC_APPWRITE_EDITORIAL_DATABASE_ID: string;
      EXPO_PUBLIC_APPWRITE_EDITORIAL_COLLECTION_ID: string;
      EXPO_PUBLIC_APPWRITE_PROMOTIONAL_BUCKET_ID: string;
      EXPO_PUBLIC_APPWRITE_LOGO_BUCKET_ID: string;
      EXPO_PUBLIC_APPWRITE_DOCUMENTATION_BUCKET_ID: string;
      EXPO_PUBLIC_APPWRITE_UPLOAD_KEY: string;
      EXPO_PUBLIC_GMAIL_ADDRESS: string;
      EXPO_PUBLIC_GMAIL_APP_PASS: string;
      EXPO_PUBLIC_RESEND_API_KEY: string;
      EXPO_PUBLIC_FLW_TEST_PUBLIC_KEY: string;
      EXPO_PUBLIC_FLW_TEST_SECRET_KEY: string;
      EXPO_PUBLIC_FLW_TEST_ENCRYPTION_KEY: string;
      EXPO_PUBLIC_FLW_PAYMENT_PLAN_ID: string;
      EXPO_PUBLIC_FLW_SECRET_HASH: string;
      EXPO_PUBLIC_STRIPE_SK: string;
      EXPO_PUBLIC_STRIPE_PK: string;
      EXPO_PUBLIC_DEEPLINK_DEVELOPMENT: string;
      EXPO_PUBLIC_ENV: "development" | "staging" | "production";
    }
  }
}
