export const screenName = {
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot-password',
    searchResults: 'Search',
    verifyEmail: 'verify-email',
    home: 'Home',
    artwork: 'Artwork',
    catalogListing: 'Catalog-listing',
    catalog: 'Catalog',
    orders: 'Orders',
    ordersListing: 'orders-listing',
    purchaseArtwork: 'purchase-artwork',
    payment: 'payment',
    profileScreen: 'profile-screen',
    profile: 'Profile',
    savedArtworks: 'saved-artworks',
    filter: 'filter',
    notifications: 'notifications',
    editorialsListing: 'editorials',
    editorial: 'editorial',
    checkout: 'checkout',
    gallery: {
        overview: 'Overview',
        artworks: 'Artworks',
        uploadArtwork: 'upload-artwork',
        orders: 'Orders',
        profile: 'Profile',
        editProfile: 'edit-profile',
        billing: 'billing',
        changePassword: 'change-gallery-password',
        subscriptions: 'Subscription',
        order: 'gallery-order',
        stripePayouts: 'stripe-payouts'
    }
}