export const screenName = {
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot-password',
    searchResults: 'SearchResults',
    home: 'Home',
    artwork: 'Artwork',
    catalogListing: 'Catalog-listing',
    catalog: 'Catalog',
    orders: 'Orders',
    ordersListing: 'orders-listing',
    purchaseArtwork: 'purchase-artwork',
    payment: 'payment',
    profileScreen: 'profile-screen',
    profile: 'profile',
    savedArtworks: 'saved-artworks',
    filter: 'filter',
}