export const screenName = {
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot-password',
    searchResults: 'Search',
    home: 'Home',
    artwork: 'Artwork',
    catalogListing: 'Catalog-listing',
    catalog: 'Catalog',
    orders: 'Orders',
    ordersListing: 'orders-listing',
    purchaseArtwork: 'purchase-artwork',
    payment: 'payment',
    profileScreen: 'profile-screen',
    profile: 'Profile',
    savedArtworks: 'saved-artworks',
    filter: 'filter',
    notifications: 'notifications',
    editorialsListing: 'editorials',
    editorial: 'editorial',
    gallery: {
        overview: 'Overview',
        artworks: 'Artworks',
        uploadArtwork: 'upload-artwork',
        orders: 'Orders',
        profile: 'Profile',
        editProfile: 'edit-profile',
        changePassword: 'change-gallery-password',
        order: 'gallery-order'
    }
}