import Constants from 'expo-constants';
import {
  EXPO_PUBLIC_URL_DEVELOPMENT,
  EXPO_PUBLIC_URL_PRODUCTION,
  EXPO_PUBLIC_API_BASE,
  EXPO_PUBLIC_API_STAGING_BASE,
  EXPO_PUBLIC_AUTH_SECRET,
  EXPO_PUBLIC_MONGODB_PASSWORD,
  EXPO_PUBLIC_UPSTASH_REDIS_REST_URL,
  EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN,
  EXPO_PUBLIC_APPWRITE_CLIENT_ID,
  EXPO_PUBLIC_APPWRITE_BUCKET_ID,
  EXPO_PUBLIC_APPWRITE_EDITORIAL_BUCKET_ID,
  EXPO_PUBLIC_APPWRITE_EDITORIAL_DATABASE_ID,
  EXPO_PUBLIC_APPWRITE_EDITORIAL_COLLECTION_ID,
  EXPO_PUBLIC_APPWRITE_PROMOTIONAL_BUCKET_ID,
  EXPO_PUBLIC_APPWRITE_LOGO_BUCKET_ID,
  EXPO_PUBLIC_APPWRITE_DOCUMENTATION_BUCKET_ID,
  EXPO_PUBLIC_APPWRITE_UPLOAD_KEY,
  EXPO_PUBLIC_GMAIL_ADDRESS,
  EXPO_PUBLIC_GMAIL_APP_PASS,
  EXPO_PUBLIC_RESEND_API_KEY,
  EXPO_PUBLIC_FLW_TEST_PUBLIC_KEY,
  EXPO_PUBLIC_FLW_TEST_SECRET_KEY,
  EXPO_PUBLIC_FLW_TEST_ENCRYPTION_KEY,
  EXPO_PUBLIC_FLW_PAYMENT_PLAN_ID,
  EXPO_PUBLIC_FLW_SECRET_HASH,
  EXPO_PUBLIC_STRIPE_SK,
  EXPO_PUBLIC_STRIPE_PK,
  EXPO_PUBLIC_DEEPLINK_DEVELOPMENT,
} from '@env';
import type { EnvironmentConfig } from '../types/environment';

const validateEnvironmentVariables = () => {
  const requiredEnvVars = {
    EXPO_PUBLIC_URL_DEVELOPMENT,
    EXPO_PUBLIC_URL_PRODUCTION,
    EXPO_PUBLIC_API_BASE,
    EXPO_PUBLIC_API_STAGING_BASE,
    EXPO_PUBLIC_AUTH_SECRET,
    EXPO_PUBLIC_MONGODB_PASSWORD,
    EXPO_PUBLIC_UPSTASH_REDIS_REST_URL,
    EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN,
    EXPO_PUBLIC_APPWRITE_CLIENT_ID,
    EXPO_PUBLIC_APPWRITE_BUCKET_ID,
    EXPO_PUBLIC_APPWRITE_EDITORIAL_BUCKET_ID,
    EXPO_PUBLIC_APPWRITE_EDITORIAL_DATABASE_ID,
    EXPO_PUBLIC_APPWRITE_EDITORIAL_COLLECTION_ID,
    EXPO_PUBLIC_APPWRITE_PROMOTIONAL_BUCKET_ID,
    EXPO_PUBLIC_APPWRITE_LOGO_BUCKET_ID,
    EXPO_PUBLIC_APPWRITE_DOCUMENTATION_BUCKET_ID,
    EXPO_PUBLIC_APPWRITE_UPLOAD_KEY,
    EXPO_PUBLIC_GMAIL_ADDRESS,
    EXPO_PUBLIC_GMAIL_APP_PASS,
    EXPO_PUBLIC_RESEND_API_KEY,
    EXPO_PUBLIC_FLW_TEST_PUBLIC_KEY,
    EXPO_PUBLIC_FLW_TEST_SECRET_KEY,
    EXPO_PUBLIC_FLW_TEST_ENCRYPTION_KEY,
    EXPO_PUBLIC_FLW_PAYMENT_PLAN_ID,
    EXPO_PUBLIC_FLW_SECRET_HASH,
    EXPO_PUBLIC_STRIPE_SK,
    EXPO_PUBLIC_STRIPE_PK,
    EXPO_PUBLIC_DEEPLINK_DEVELOPMENT,
  };

  const missingVars = Object.entries(requiredEnvVars)
    .filter(([_, value]) => !value)
    .map(([key]) => key);

  if (missingVars.length > 0) {
    throw new Error(
      `Missing required environment variables: ${missingVars.join(', ')}\n\n` +
      'See .env.example for reference.'
    );
  }
};

try {
  validateEnvironmentVariables();
} catch (error) {
  console.error('Environment configuration error: Missing required environment variables');
  throw error;
}

const getEnvironmentConfig = (): EnvironmentConfig => {
  const currentEnv = Constants.expoConfig?.extra?.EXPO_PUBLIC_ENV || 'development';
  
  return {
    urlDevelopment: EXPO_PUBLIC_URL_DEVELOPMENT,
    urlProduction: EXPO_PUBLIC_URL_PRODUCTION,
    apiBase: EXPO_PUBLIC_API_BASE,
    apiStagingBase: EXPO_PUBLIC_API_STAGING_BASE,
    authSecret: EXPO_PUBLIC_AUTH_SECRET,
    mongodbPassword: EXPO_PUBLIC_MONGODB_PASSWORD,
    upstashRedisRestUrl: EXPO_PUBLIC_UPSTASH_REDIS_REST_URL,
    upstashRedisRestToken: EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN,
    appwriteClientId: EXPO_PUBLIC_APPWRITE_CLIENT_ID,
    appwriteBucketId: EXPO_PUBLIC_APPWRITE_BUCKET_ID,
    appwriteEditorialBucketId: EXPO_PUBLIC_APPWRITE_EDITORIAL_BUCKET_ID,
    appwriteEditorialDatabaseId: EXPO_PUBLIC_APPWRITE_EDITORIAL_DATABASE_ID,
    appwriteEditorialCollectionId: EXPO_PUBLIC_APPWRITE_EDITORIAL_COLLECTION_ID,
    appwritePromotionalBucketId: EXPO_PUBLIC_APPWRITE_PROMOTIONAL_BUCKET_ID,
    appwriteLogoBucketId: EXPO_PUBLIC_APPWRITE_LOGO_BUCKET_ID,
    appwriteDocumentationBucketId: EXPO_PUBLIC_APPWRITE_DOCUMENTATION_BUCKET_ID,
    appwriteUploadKey: EXPO_PUBLIC_APPWRITE_UPLOAD_KEY,
    gmailAddress: EXPO_PUBLIC_GMAIL_ADDRESS,
    gmailAppPass: EXPO_PUBLIC_GMAIL_APP_PASS,
    resendApiKey: EXPO_PUBLIC_RESEND_API_KEY,
    flwTestPublicKey: EXPO_PUBLIC_FLW_TEST_PUBLIC_KEY,
    flwTestSecretKey: EXPO_PUBLIC_FLW_TEST_SECRET_KEY,
    flwTestEncryptionKey: EXPO_PUBLIC_FLW_TEST_ENCRYPTION_KEY,
    flwPaymentPlanId: EXPO_PUBLIC_FLW_PAYMENT_PLAN_ID,
    flwSecretHash: EXPO_PUBLIC_FLW_SECRET_HASH,
    stripeSecretKey: EXPO_PUBLIC_STRIPE_SK,
    stripePublicKey: EXPO_PUBLIC_STRIPE_PK,
    deeplinkDevelopment: EXPO_PUBLIC_DEEPLINK_DEVELOPMENT,
    environment: currentEnv,
  };
};

export const envConfig = getEnvironmentConfig();
