export const getFlag = (code: string): string => {
  const flags: Record<string, string> = {
    AUD: "🇦🇺",
    EUR: "🇪🇺",
    XOF: "🌍",
    BWP: "🇧🇼",
    CAD: "🇨🇦",
    HRK: "🇭🇷",
    CZK: "🇨🇿",
    DKK: "🇩🇰",
    EGP: "🇪🇬",
    ETB: "🇪🇹",
    GMD: "🇬🇲",
    GHS: "🇬🇭",
    ISK: "🇮🇸",
    JPY: "🇯🇵",
    KES: "🇰🇪",
    MUR: "🇲🇺",
    MAD: "🇲🇦",
    MZN: "🇲🇿",
    NAD: "🇳🇦",
    NZD: "🇳🇿",
    NGN: "🇳🇬",
    NOK: "🇳🇴",
    PLN: "🇵🇱",
    QAR: "🇶🇦",
    RWF: "🇷🇼",
    SGD: "🇸🇬",
    ZAR: "🇿🇦",
    KRW: "🇰🇷",
    SEK: "🇸🇪",
    CHF: "🇨🇭",
    TZS: "🇹🇿",
    TRY: "🇹🇷",
    AED: "🇦🇪",
    GBP: "🇬🇧",
    USD: "🇺🇸",
  };

  return flags[code.toUpperCase()] || "🏳️";
};
